spring.application.name=social-media-app-backend
spring.data.mongodb.database=social-media

# testing purpose without AWS connection:
#aws.mock=true

#aws config
aws.s3.accessKey=${AWS_ACCESS_KEY}
aws.s3.secretKey=${AWS_SECRET_KEY}
aws.s3.region=eu-north-1

# set file max sizes
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB